### ISSUE TITLE
Foutmelding geven als niet alle trainingsvelden zijn ingevuld

### ISSUE THREAD

**Issue by chrisrutte** [chrisrutte/musc#7]
Nu slaat ie hem dan gewoon niet op

**Comment by robbertmusc** [comment]
Fixed! :) Kan alleen geen documenten uploaden naar githup... Kan je mij daar toestemming voor geven ofzo?
Heb ook meteen van het tijdstip veld een time-veld gemaakt

**Comment by chrisrutte** [comment]
dit ook doen bij
- toevoegen datums (bijv. als je alleen een datum maar geen tijd invult)
- aanpassen # deelnemers als er max_att naar beneden wordt bijgesteld terwijl er al inschrijvingen zijn? --> ik denk dat we in dit geval een melding moeten geven dat trainingen waar al meer deelnemers aren ingeschreven zo blijven

**Comment by chrisrutte** [comment]
Nu geeft ie ook mooie foutmeldingen!
